#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 24
#$ -q lThC.q
#$ -l mres=72G,h_data=3G,h_vmem=3G
#$ -cwd
#$ -j y
#$ -N iqtree_ourySNPs
#$ -o iqtree_ourySNPs.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/iqtree
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

iqtree2 \
-s ${prodir}/outputs/oury_pipeline/contigs_DP3_SP6_miss15_merged361ref.min4.phy \
--seqtype DNA \
-m MFP \
-bb 1000 \
-alrt 1000 \
-nt $NSLOTS \
--prefix ${prodir}/outputs/iqtree/iqtree_oury_contigs

echo = `date` job $JOB_NAME done