#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 24
#$ -q lThC.q
#$ -l mres=72G,h_data=3G,h_vmem=3G
#$ -cwd
#$ -j y
#$ -N iqtree_phyluce
#$ -o iqtree_phyluce.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/iqtree
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/pocillopora_hDNA_uces"

# specify which taxon set and alignment to use
set=$1
#
iqtree2 \
-s ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${2}p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${2}p.phylip \
-p ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${2}p-raxml/${set}-mafft-nexus-internal-trimmed-gblocks-clean-${2}p.partitions \
--seqtype DNA \
-m MFP+MERGE \
-bb 1000 \
-alrt 1000 \
-nt $NSLOTS \
-keep-ident \
--prefix ${prodir}/outputs/iqtree/iqtree_${set}_${2}

echo = `date` job $JOB_NAME done