#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N Oury_SNP_pipeline
#$ -o Oury_SNP_pipeline.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
module load bioinformatics/bcftools
module load bioinformatics/vcftools
#
# ----------------Your Commands------------------- #

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim"

# making a list of sample names
set=$1
samples=$(cat ${prodir}/data/${set}_samples.txt)

# Make bam file list
touch ${prodir}/outputs/oury_pipeline/${set}_List_bam.txt 
for sample in ${samples} ; do ls ${prodir}/outputs/oury_pipeline/${sample}*_realigned_reads.bam >> ${prodir}/outputs/oury_pipeline/${set}_List_bam.txt ; done
cat ${prodir}/outputs/oury_pipeline/${set}_List_bam.txt | sort | uniq > ${prodir}/outputs/oury_pipeline/${set}_bams.txt

#3°) SNP genotype calling & filtering
#3.1°) SNP genotype calling (where *List_bam.txt is the list of the bam files)
bcftools mpileup -A -B -I -Ou -a AD,DP,SP,INFO/AD -f ${mcs}/sequences/Pocillopora_UCEs_exons_2068_ref_sequences.fasta -R ${prodir}/data/List_1559SNP_noLD.txt -b ${prodir}/outputs/oury_pipeline/${set}_bams.txt | bcftools call -m --threads 16 -Ob -o  ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP.bcf

#3.2°) Filtering genotypes based on DP & SP
#Filtering based on DP
bcftools filter -S '.' -e 'FORMAT/DP<3'  ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP.bcf | bcftools view -i 'AN>2 & AC!=0 & AN!=AC' --threads 16 -Ob -o ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3.bcf

#Filtering based on SP
bcftools filter -S '.' -e 'FORMAT/SP>6'  ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3.bcf | bcftools view -i 'AN>2 & AC!=0 & AN!=AC' --threads 16 -Ob -o ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3_SP6.bcf

#4°) Merge with Oury reference SNPs for direct downstream comparisons

bcftools sort ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3_SP6.bcf -Oz -o ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3_SP6_sorted.vcf.gz

bcftools index -t ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3_SP6_sorted.vcf.gz

bcftools merge ${prodir}/outputs/oury_pipeline/${set}_Calls_1559SNP_DP3_SP6_sorted.vcf.gz ${prodir}/data/Pocillopora_361ADN_1559SNP.vcf.gz  -Oz -m snps -o ${prodir}/outputs/oury_pipeline/${set}_DP3_SP6_merged361ref.vcf.gz

# Echo finished 
echo "Finished!"
#
echo = `date` job $JOB_NAME done

# 1089  bcftools stats Pocillopora_361ADN_1559SNP.vcf 
 #1090  cp Pocillopora_361ADN_1559SNP.vcf Pocillopora_361ADN_1559SNP_original.vcf 
 #1091  bcftools view Pocillopora_361ADN_1559SNP.vcf -Oz -o Pocillopora_361ADN_1559SNP.vcf.gz
 #1092  bcftools index Pocillopora_361ADN_1559SNP.vcf.gz 
 #1096  bcftools merge all_noclones_Calls_1559SNP_DP3_SP6_sorted.vcf.gz ../../data/Pocillopora_361ADN_1559SNP.vcf.gz -m all -Oz -o ${prodir}/outputs/oury_pipeline/${set}_DP3_SP6_merged361ref.vcf.gz
 #1099  bcftools stats all_noclones_DP3_SP6_merged361ref.vcf.gz 