#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N phyluce_clean_alignment
#$ -o phyluce_clean_alignment.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bioinformatics/phyluce
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/pocillopora_hDNA_uces"

# making a list of sample names
set=$1
#files=$(ls /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/data/raw/)
#samples=$(echo "$files" | cut -d . -f 1 | sort -u)
#samples=$(cat ${prodir}/data/${set}_samples.txt)

# align the data - turn off trimming and output FASTA
phyluce_align_remove_locus_name_from_nexus_lines  \
    --alignments ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks \
    --output ${prodir}/outputs/uce-taxon-sets/${set}-mafft-nexus-internal-trimmed-gblocks-clean \
    --cores $NSLOTS \
    --log-path ${prodir}/outputs/uce-taxon-sets/log

echo = `date` job $JOB_NAME done

# start next job in pipeline - produce concatenated matrix
qsub ${prodir}/jobs/phyluce_05_complete_concat_matrix.job $set 75