#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 16
#$ -q mThM.q
#$ -l mres=192G,h_data=12G,h_vmem=12G,himem
#$ -cwd
#$ -j y
#$ -N phyluce_assembly_get_matches_fastas
#$ -o phyluce_assembly_get_matches_fastas.log
#$ -m bea
#$ -M connellym@si.edu
#
# ----------------Modules------------------------- #
 module load bioinformatics/phyluce
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS

#specify variable containing sequence file prefixes and directory paths
mcs="/scratch/nmnh_corals/connellym"
prodir="/scratch/nmnh_corals/connellym/projects/pocillopora_hDNA_uces"

# making a list of sample names
set=$1
#files=$(ls /scratch/nmnh_corals/connellym/projects/etp_pocillopora_gskim/data/raw/)
#samples=$(echo "$files" | cut -d . -f 1 | sort -u)
samples=$(cat ${prodir}/data/${set}_samples.txt)

# create the basic configuration file
echo '[all]' > ${prodir}/data/${set}.conf
for sample in $samples; do echo ${sample}_contigs  >> ${prodir}/data/${set}.conf ; done
# add Connelly reference samples
for i in ${prodir}/data/contemporary_contigs/*.fasta; do basename $i | cut -d . -f 1 >> ${prodir}/data/${set}.conf; done
# add Oury reference samples
#for i in ${prodir}/data/oury_contigs/*.fasta; do basename $i | cut -d . -f 1 >> ${prodir}/data/${set}.conf; done

# add outgroup taxa
#echo "Seriatopora_hystrix_ReFuGe_contigs" >> ${prodir}/data/${set}.conf
echo "Stylophora_pistillata_ANT17_contigs" >> ${prodir}/data/${set}.conf
TAXA=$(ls ${prodir}/data/outgroups/scleractinia-genome-fasta/p* | cut -d . -f 1)
for taxon in $TAXA; do echo $taxon >> ${prodir}/data/${set}.conf; done

# create the data matrix configuration file
phyluce_assembly_get_match_counts \
    --locus-db ${prodir}/outputs/uce-search-results/${set}/probe.matches.sqlite \
    --taxon-list-config ${prodir}/data/${set}.conf \
    --taxon-group 'all' \
    --incomplete-matrix \
    --output ${prodir}/outputs/uce-taxon-sets/${set}-taxa-incomplete.conf

# get FASTA data for taxa in our taxon set
phyluce_assembly_get_fastas_from_match_counts \
    --contigs ${prodir}/outputs/spades/contigs/${set}/ \
    --locus-db ${prodir}/outputs/uce-search-results/${set}/probe.matches.sqlite \
    --match-count-output ${prodir}/outputs/uce-taxon-sets/${set}-taxa-incomplete.conf \
    --output ${prodir}/outputs/uce-taxon-sets/${set}-taxa-incomplete.fasta \
    --incomplete-matrix ${prodir}/outputs/uce-taxon-sets/${set}-taxa-incomplete.incomplete \
    --log-path ${prodir}/outputs/uce-taxon-sets/log

echo = `date` job $JOB_NAME done

# start next job in pipeline - MAFFT alignment and trimming
qsub ${prodir}/jobs/phyluce_03b_align_mafft_gblocks.job $set